import 'package:nak_electronics/models/product.dart';

class ProductService {
  static final List<Product> _products = [
    // Keyboards
    Product(
      id: '1',
      name: 'Yamaha PSR-EW425',
      price: 450.0,
      image: 'assets/images/Keyboard1.png',
      category: 'Keyboard',
      brand: 'Yamaha',
      description: 'Portable keyboard with 76 keys',
      isNew: true,
    ),
    Product(
      id: '2',
      name: 'Casio CT-X3000',
      price: 350.0,
      image: 'assets/images/keyboard.png',
      category: 'Keyboard',
      brand: 'Casio',
      description: '61-key portable keyboard',
      isNew: false,
    ),
    // Guitars
    Product(
      id: '3',
      name: 'Fender Player Stratocaster',
      price: 650.0,
      image: 'assets/images/fender player.png',
      category: 'Guitars & Bass',
      brand: 'Fender',
      description: 'Electric guitar',
      isNew: true,
    ),
    Product(
      id: '4',
      name: 'Gibson Les Paul',
      price: 1200.0,
      image: 'assets/images/gibsonsg.png',
      category: 'Guitars & Bass',
      brand: 'Gibson',
      description: 'Classic electric guitar',
      isNew: false,
    ),
    // Drums
    Product(
      id: '5',
      name: 'Pearl Export',
      price: 800.0,
      image: 'assets/images/pearl.png',
      category: 'Drums & Percussion',
      brand: 'Pearl',
      description: '5-piece drum kit',
      isNew: false,
    ),
    Product(
      id: '6',
      name: 'TAMA Imperialstar',
      price: 950.0,
      image: 'assets/images/tamadrum.png',
      category: 'Drums & Percussion',
      brand: 'TAMA',
      description: '6-piece drum kit',
      isNew: true,
    ),
    // Headphones
    Product(
      id: '7',
      name: 'JBL T600',
      price: 50.0,
      image: 'assets/images/headphone.png',
      category: 'Headphones',
      brand: 'JBL',
      description: 'Wireless headphones',
      isNew: false,
    ),
    Product(
      id: '8',
      name: 'Sony WH-1000XM4',
      price: 250.0,
      image: 'assets/images/headset.png',
      category: 'Headphones',
      brand: 'Sony',
      description: 'Noise-cancelling headphones',
      isNew: true,
    ),
    // Microphones
    Product(
      id: '9',
      name: 'Shure SM58',
      price: 100.0,
      image: 'assets/images/shure.png',
      category: 'Microphones',
      brand: 'Shure',
      description: 'Dynamic microphone',
      isNew: false,
    ),
    Product(
      id: '10',
      name: 'AKG C214',
      price: 400.0,
      image: 'assets/images/microphone.png',
      category: 'Microphones',
      brand: 'AKG',
      description: 'Condenser microphone',
      isNew: false,
    ),
    // Amplifiers
    Product(
      id: '11',
      name: 'Fender Tone Master Deluxe',
      price: 300.0,
      image: 'assets/images/amp.png',
      category: 'Amplifiers',
      brand: 'Fender',
      description: 'Guitar amplifier',
      isNew: false,
    ),
    // Mixers
    Product(
      id: '12',
      name: 'Yamaha MG06X',
      price: 200.0,
      image: 'assets/images/mg_series.png',
      category: 'Mixers',
      brand: 'Yamaha',
      description: '6-channel mixer',
      isNew: false,
    ),
    // PA Systems
    Product(
      id: '13',
      name: 'JBL EON615',
      price: 500.0,
      image: 'assets/images/jbl.png',
      category: 'PA System & Live Sound',
      brand: 'JBL',
      description: '15" powered speaker',
      isNew: true,
    ),
    Product(
      id: '14',
      name: 'Electro-Voice ZLX-12P',
      price: 400.0,
      image: 'assets/images/ev.png',
      category: 'PA System & Live Sound',
      brand: 'EV',
      description: '12" powered speaker',
      isNew: false,
    ),
    // Accessories - let's add some
    Product(
      id: '15',
      name: 'Keyboard Stand',
      price: 30.0,
      image: 'assets/images/keyboard.png', // placeholder
      category: 'Keyboard',
      brand: 'Generic',
      description: 'Adjustable keyboard stand',
      isNew: false,
    ),
    Product(
      id: '16',
      name: 'Guitar Strings',
      price: 10.0,
      image: 'assets/images/guitar.png', // placeholder
      category: 'Guitars & Bass',
      brand: 'Generic',
      description: 'Set of guitar strings',
      isNew: false,
    ),
    // More Guitars
    Product(
      id: '17',
      name: 'Ibanez RG550',
      price: 850.0,
      image: 'assets/images/ibanez.png',
      category: 'Guitars & Bass',
      brand: 'Ibanez',
      description: 'Electric guitar with premium pickups',
      isNew: true,
      discount: 0.15,
    ),
    Product(
      id: '18',
      name: 'Fender Precision Bass',
      price: 750.0,
      image: 'assets/images/guitar.png',
      category: 'Guitars & Bass',
      brand: 'Fender',
      description: 'Classic bass guitar',
      isNew: false,
    ),
    Product(
      id: '19',
      name: 'Gibson SG Standard',
      price: 1100.0,
      image: 'assets/images/gibsonsg.png',
      category: 'Guitars & Bass',
      brand: 'Gibson',
      description: 'Iconic SG electric guitar',
      isNew: true,
      discount: 0.12,
    ),
    // More Keyboards
    Product(
      id: '20',
      name: 'Roland FP-30X',
      price: 680.0,
      image: 'assets/images/keyboard.png',
      category: 'Keyboard',
      brand: 'Roland',
      description: '88-key digital piano',
      isNew: true,
      discount: 0.10,
    ),
    Product(
      id: '21',
      name: 'Korg B2',
      price: 520.0,
      image: 'assets/images/Keyboard1.png',
      category: 'Keyboard',
      brand: 'Korg',
      description: '88-key digital piano with weighted keys',
      isNew: false,
    ),
    // More Drums
    Product(
      id: '22',
      name: 'Pearl Decade Maple',
      price: 1200.0,
      image: 'assets/images/pearl.png',
      category: 'Drums & Percussion',
      brand: 'Pearl',
      description: '7-piece maple drum kit',
      isNew: true,
      discount: 0.18,
    ),
    Product(
      id: '23',
      name: 'TAMA Starclassic',
      price: 1500.0,
      image: 'assets/images/tamadrum.png',
      category: 'Drums & Percussion',
      brand: 'TAMA',
      description: 'Professional drum kit',
      isNew: false,
    ),
    // More Headphones
    Product(
      id: '24',
      name: 'Audio-Technica ATH-M50x',
      price: 150.0,
      image: 'assets/images/headphone.png',
      category: 'Headphones',
      brand: 'Audio-Technica',
      description: 'Professional monitoring headphones',
      isNew: true,
      discount: 0.20,
    ),
    Product(
      id: '25',
      name: 'Beyerdynamic DT 770 Pro',
      price: 180.0,
      image: 'assets/images/headset.png',
      category: 'Headphones',
      brand: 'Beyerdynamic',
      description: 'Studio headphones',
      isNew: false,
    ),
    // More Microphones
    Product(
      id: '26',
      name: 'Audio-Technica AT2020',
      price: 120.0,
      image: 'assets/images/microphone.png',
      category: 'Microphones',
      brand: 'Audio-Technica',
      description: 'Cardioid condenser microphone',
      isNew: true,
    ),
    Product(
      id: '27',
      name: 'Rode NT1-A',
      price: 250.0,
      image: 'assets/images/condenser.png',
      category: 'Microphones',
      brand: 'Rode',
      description: 'Large diaphragm condenser mic',
      isNew: false,
      discount: 0.15,
    ),
    // More Amplifiers
    Product(
      id: '28',
      name: 'Marshall DSL40CR',
      price: 650.0,
      image: 'assets/images/amp.png',
      category: 'Amplifiers',
      brand: 'Marshall',
      description: '40W tube combo amplifier',
      isNew: true,
      discount: 0.12,
    ),
    Product(
      id: '29',
      name: 'Orange Crush 35RT',
      price: 220.0,
      image: 'assets/images/amp.png',
      category: 'Amplifiers',
      brand: 'Orange',
      description: '35W solid-state combo amp',
      isNew: false,
    ),
    // More Mixers
    Product(
      id: '30',
      name: 'Yamaha MG16XU',
      price: 350.0,
      image: 'assets/images/mg_series.png',
      category: 'Mixers',
      brand: 'Yamaha',
      description: '16-channel mixer with USB',
      isNew: true,
      discount: 0.10,
    ),
    Product(
      id: '31',
      name: 'Behringer Xenyx X1832USB',
      price: 280.0,
      image: 'assets/images/mixer.png',
      category: 'Mixers',
      brand: 'Behringer',
      description: '18-channel mixer',
      isNew: false,
    ),
    // More PA Systems
    Product(
      id: '32',
      name: 'JBL PRX815W',
      price: 850.0,
      image: 'assets/images/jbl.png',
      category: 'PA System & Live Sound',
      brand: 'JBL',
      description: '15" powered speaker with WiFi',
      isNew: true,
      discount: 0.15,
    ),
    Product(
      id: '33',
      name: 'QSC K12.2',
      price: 750.0,
      image: 'assets/images/sound.png',
      category: 'PA System & Live Sound',
      brand: 'QSC',
      description: '12" powered speaker',
      isNew: false,
    ),
    // Recording Gear
    Product(
      id: '34',
      name: 'Focusrite Scarlett 2i2',
      price: 180.0,
      image: 'assets/images/recording.png',
      category: 'Recording Gear',
      brand: 'Focusrite',
      description: '2-in/2-out USB audio interface',
      isNew: true,
      discount: 0.18,
    ),
    Product(
      id: '35',
      name: 'PreSonus AudioBox USB 96',
      price: 100.0,
      image: 'assets/images/card.png',
      category: 'Recording Gear',
      brand: 'PreSonus',
      description: '2x2 USB audio interface',
      isNew: false,
    ),
    // Studio Monitors
    Product(
      id: '36',
      name: 'KRK Rokit 5 G4',
      price: 300.0,
      image: 'assets/images/monitor.png',
      category: 'Studio Monitors',
      brand: 'KRK',
      description: '5" powered studio monitor',
      isNew: true,
      discount: 0.12,
    ),
    Product(
      id: '37',
      name: 'Yamaha HS5',
      price: 280.0,
      image: 'assets/images/monitor.png',
      category: 'Studio Monitors',
      brand: 'Yamaha',
      description: '5" studio monitor',
      isNew: false,
    ),
    // Lighting
    Product(
      id: '38',
      name: 'Chauvet DJ SlimPAR Pro',
      price: 150.0,
      image: 'assets/images/lighting.png',
      category: 'Lighting & Effect',
      brand: 'Chauvet',
      description: 'RGB LED par light',
      isNew: true,
    ),
    Product(
      id: '39',
      name: 'ADJ Mega Par Profile',
      price: 200.0,
      image: 'assets/images/light.png',
      category: 'Lighting & Effect',
      brand: 'ADJ',
      description: 'RGBW LED par light',
      isNew: false,
      discount: 0.10,
    ),
    // More Accessories
    Product(
      id: '40',
      name: 'Guitar Cable 10ft',
      price: 25.0,
      image: 'assets/images/guitar.png',
      category: 'Guitars & Bass',
      brand: 'Generic',
      description: 'High-quality instrument cable',
      isNew: false,
    ),
    Product(
      id: '41',
      name: 'Drum Sticks 5A',
      price: 15.0,
      image: 'assets/images/drums.png',
      category: 'Drums & Percussion',
      brand: 'Vic Firth',
      description: 'Pair of 5A drum sticks',
      isNew: false,
    ),
    Product(
      id: '42',
      name: 'Microphone Stand',
      price: 45.0,
      image: 'assets/images/microphone.png',
      category: 'Microphones',
      brand: 'Generic',
      description: 'Adjustable boom stand',
      isNew: false,
    ),
  ];

  static List<Product> getAllProducts() {
    return _products;
  }

  static List<Product> getProductsByCategory(String category) {
    return _products.where((p) => p.category == category).toList();
  }

  static List<Product> getProductsByBrand(String brand) {
    return _products.where((p) => p.brand == brand).toList();
  }

  static List<Product> getNewArrivals() {
    return _products.where((p) => p.isNew).toList();
  }

  static Product? getProductById(String id) {
    return _products.firstWhere((p) => p.id == id);
  }
}
