// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG70nYTiEMWhjfkY5cQfHl-1njpRZJ20Y',
    appId: '1:273958353608:web:876c2afc386b925b7f83fd',
    messagingSenderId: '273958353608',
    projectId: 'naknaa-online',
    authDomain: 'naknaa-online.firebaseapp.com',
    storageBucket: 'naknaa-online.firebasestorage.app',
    measurementId: 'G-RBNZ7T4DL6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfbMuUmchPxMet0KgB7kARTfu1X2EUSg4',
    appId: '1:273958353608:android:906781d0656f4ede7f83fd',
    messagingSenderId: '273958353608',
    projectId: 'naknaa-online',
    storageBucket: 'naknaa-online.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb9E2LPYUQJ7P_VROD5Hv2wNTd_9luZvw',
    appId: '1:273958353608:ios:6c87c7d8c9cf82e07f83fd',
    messagingSenderId: '273958353608',
    projectId: 'naknaa-online',
    storageBucket: 'naknaa-online.firebasestorage.app',
    iosBundleId: 'com.mindease.mindeaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb9E2LPYUQJ7P_VROD5Hv2wNTd_9luZvw',
    appId: '1:273958353608:ios:0b28db8e24c35b0f7f83fd',
    messagingSenderId: '273958353608',
    projectId: 'naknaa-online',
    storageBucket: 'naknaa-online.firebasestorage.app',
    iosBundleId: 'com.example.nakElectronics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCG70nYTiEMWhjfkY5cQfHl-1njpRZJ20Y',
    appId: '1:273958353608:web:32fb3aaf96831ace7f83fd',
    messagingSenderId: '273958353608',
    projectId: 'naknaa-online',
    authDomain: 'naknaa-online.firebaseapp.com',
    storageBucket: 'naknaa-online.firebasestorage.app',
    measurementId: 'G-QF98Z9EMRB',
  );
}
